---
include:
  - project: c2/hll21054-hll-hello-kyc/operation-2023/pipeline-template
    ref: main
    file:
      - 'build/build.gitlab-ci.yml'
      - 'build-arm/build-arm.gitlab-ci.yml'
      - 'sast/sast.gitlab-ci.yml'

build:
  extends:
    - .build
build_arm:
  extends:
    - .build_arm

# multi_arch: 
#   extends: 
#     - .push_multi_arch
#   needs:
#     - build
#     - build_arm
dependency-check:
  extends:
    - .dependency-check
sonarqube-scan:
  extends:
    - .sonarqube-scan

snyk-scan:
  extends:
    - .snyk-scan

trivy-scan:
  extends:
    - .trivy-scan