include:
- project: c2/hll21054-hll-hello-kyc/operation-2023/pipeline-template
  ref: main
  file: 
  - 'build/build.gitlab-ci.yml'
  - 'docker/docker.gitlab-ci.yml'

stages:
  - &step1 build

deploy-service:
  stage: *step1
  extends:
    - .rules_template
    - .docker_templates
    - .before_script_template
    - .script_template
    - .caching_template
