---
include:
  - project: c2/hll21054-hll-hello-kyc/operation-2023/pipeline-template
    ref: ft/sonarqube
    file:
      - 'build/build.gitlab-ci.yml'
      - 'sast/sast.gitlab-ci.yml'

stages:
  - &prebuild prebuild-scan
  - &build build
  - &post-build post-build
