---
include:
  - project: c2/hll21054-hll-hello-kyc/operation-2023/pipeline-template
    ref: ft/sonarqube
    file:
      - 'build/build.gitlab-ci.yml'
      - 'sast/sast.gitlab-ci.yml'

stages:
  - &prebuild prebuild-scan
  - &build build
  - &post-build post-build

dependency-check:
  extends: .dependency-check
  stage: *prebuild

sonarqube-scan:
  extends: .sonarqube-scan
  stage: *prebuild

snyk-scan:
  extends: .snyk-scan
  stage: *prebuild

build:
  extends: .build
  stage: *build

trivy-scan:
  extends: .trivy-scan
  stage: *post-build
