---
include:
  - project: c2/hll21054-hll-hello-kyc/operation-2023/pipeline-template
    ref: main
    file:
      - 'build/build.gitlab-ci.yml'
      - 'build-arm/build-arm.gitlab-ci.yml'
      - 'sast/sast.gitlab-ci.yml'

build:
  extends:
    - .build
  allow_failure: false
  retry: 2
  
build_arm:
  extends:
    - .build_arm
  allow_failure: false
  retry: 2

multi_arch: 
  extends: 
    - .push_multi_arch
  needs:
    - build
    - build_arm
  allow_failure: false
dependency-check:
  extends:
    - .dependency-check
sonarqube-scan:
  extends:
    - .sonarqube-scan

snyk-scan:
  extends:
    - .snyk-scan

trivy-scan:
  extends:
    - .trivy-scan

release:
  image: node:14-buster-slim
  before_script:
    - yarn install
  script:
    - yarn release
  tags:
    - hll-runner-core
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^release-*/'
  