.docker_templates:
  variables:
    # common variable
    DOCKER_HOST: tcp://localhost:2375
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  tags:
    - hll-runner-core
  services:
    - docker:stable-dind
  image:
    name: public.ecr.aws/g5j7s8k4/ci-node:v14-gitops
  artifacts:
    paths:
      - dist