.docker_templates: &docker_templates
  variables:
    # common variable
    DOCKER_HOST: tcp://localhost:2375
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  tags:
    - hll-runner-core
  services:
    - docker:stable-dind

