include:
  - project: c2/hll21054-hll-hello-kyc/operation-2023/pipeline-template
    ref: main
    file:
      - 'build/build.gitlab-ci.yml'
.docker_templates_arm:
  variables:
    # common variable
    DOCKER_HOST: tcp://localhost:2375
  image:
    name: ladung/node16-buildkit12:docker-aws
  artifacts:
    paths:
      - dist
.script_template_arm:
  script:
    # const
    - !reference [.image_info_template, script]
    # lint & pre-build
    - yarn
    - yarn lint
    - yarn build:$ENV
    # - docker pull $IMAGE_FIX || true
    # - >
    #   docker build --cache-from=$IMAGE_FIX
    #   -t $IMAGE_FIX -f .docker/$ENV.dockerfile .
    - ls -la
    - >
      aws ecr get-login-password --region $AWS_DEFAULT_REGION |
      docker login --username AWS --password-stdin $DOCKER_REGISTRY_HOST
    # - buildctl --addr tcp://buildkitd:1234 build --frontend dockerfile.v0 --opt platform=linux/amd64,linux/arm64 --local context=. --local dockerfile=. --opt filename=.docker/dev.dockerfile --output type=image,name=$IMAGE_FIX,push=true
    - buildctl --addr tcp://buildkitd:1234 build --frontend dockerfile.v0 --opt platform=linux/amd64,linux/arm64 --local context=. --local dockerfile=. --opt filename=.docker/dev.dockerfile --output type=image,name=$IMAGE_BACKUP,push=true

.tags_template_arm: &tags_template_arm
  tags:
    - hll-runner-core

.rules_template_arm: &rules_template_arm
  rules:
    - if: '$CI_COMMIT_BRANCH == "dungla"'
      when: always
    - if: '$CI_COMMIT_BRANCH != "deployment/dev"
          || $CI_COMMIT_BRANCH != "deployment/staging"
          || $CI_COMMIT_BRANCH != "master"'
      when: never

.before_script_template_arm: &before_script_template_arm
  before_script:
    - if [ "$CI_COMMIT_BRANCH" == "dungla" ]; then ENV="dev"; fi
    - if [ "$CI_COMMIT_BRANCH" == "deployment/staging" ]; then ENV="staging"; fi
    - if [ "$CI_COMMIT_BRANCH" == "master" ]; then ENV="production"; fi


.build_arm:
  extends:
    - .docker_templates_arm
    - .before_script_template_arm
    - .rules_template_arm
    - .tags_template_arm
    - .script_template_arm