---
include:
  - project: c2/hll21054-hll-hello-kyc/operation-2023/pipeline-template
    ref: main
    file:
      - 'docker/docker.gitlab-ci.yml'

.rule_develop: &rule_develop
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'
      when: on_success
    - if: '$CI_COMMIT_BRANCH != "develop"'
      when: never

.disable_sonarqube: &disable_sonarqube
  rules:
    - if: '$CI_DISABLE_SONARQUBE == "true"'
      when: never

.all_rules: &all_rules
  rules:
    - !reference [.rule_develop, rules]
    - !reference [.disable_sonarqube, rules]

.artifact: &artifact
  artifacts:
    paths:
      - $CI_PROJECT_DIR/.sonarqube

sonarqube-scan:
  extends: .docker_templates
  stage: sonarqube-scan
  image: sonarsource/sonar-scanner-cli
  services: null
  variables:                             # Tells git to fetch all the branches of the project, required by the analysis task
    SONAR_SCANNER_OPTS: "-Dsonar.projectKey=$CI_PROJECT_NAME"
  script:
    - sonar-scanner
  allow_failure: true
  <<: *all_rules
  <<: *artifact
